// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vinyls.Data;

#nullable disable

namespace vinylsapi.Migrations
{
    [DbContext(typeof(VinylsDbContext))]
    [Migration("20250628023708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vinyls.Entities.Vinyl", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Vinyls");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Artist = "The Beatles",
                            Name = "Abbey Road",
                            Year = 1969
                        },
                        new
                        {
                            ID = 2,
                            Artist = "Pink Floyd",
                            Name = "Dark Side Of The Moon",
                            Year = 1973
                        },
                        new
                        {
                            ID = 3,
                            Artist = "Michael Jackson",
                            Name = "Thriller",
                            Year = 1982
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
